<h2>About the Department</h2>
<p>&nbsp;&nbsp;&nbsp;&nbsp;The Department of Computer Science and Engineering is the most prestigious department under Mangalam College of Engineering. This is the branch of engineering with the most advanced syllabi. It provides practical assignments and makes the students proficient in programming, networking etc, which makes them compete with todays growing industry demands. </p>
<h2>About Comets </h2>
<img src="img/comets_logo.jpg" alt="Comets Revised Logo" width="154" height="148" class="floatR" />
<p>&nbsp;&nbsp;&nbsp;&nbsp;The Computer Science Engineering Association was formed in 2006 and is called Comets which stands for Computer Engineering Techies. The inauguration ceremony of the association was a fantastic event filled with cultural and technical programmes. Students from all the branches of the college competed in the Intracollege technical and management competitions that were organised with the inauguration. The logo of Comets was revised this year by <a href="http://www.geocities.com/mhkonline2/ae/index.html" target="_blank">Artistik Expressionz</a>. The current span of the association has plans to conduct Seminars by prominent speakers on latest technologies to make the students aware of the opportunities that are before them and how to successfully utilise them. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;The revised logo reflects the new life brought into the association with the newly elected members and the new juniors who have stepped onto the long road ahead of them which will lead them to prominent success.</p>
<h3>Artistik Expressionz </h3>
<p><img src="img/ae_logo_transitional.jpg" alt="Artistik Expressionz" width="398" height="90" class="floatL" /></p>
<p align="justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Artistik Expressionz is the root of our designing and development. Any kind of designing work or that with an interactive end   is assigned to it. It was firstly called by its full name. But now, with the   advent of the new logo and new style, its simply called ae. Ae has sort of   become synonymous with simplicity. The logo shown above is the transitional version can be used with the display theme of any work that we do. </p>
<p align="justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ae is all about&nbsp; the integrity of pure design. It shows   how much importance we give to good designing as Ae has been formed exclusively   to take care of that. We are poised to make good designs by combining the best   of both worlds. The new logo signifies this outlook. It is a radical element   that acts like an icon.</p>
<p align="justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The commitments that ae has made for this project includes logo, poster, brochure designs for Ambience '07, logo for Comets both original and redesigned. Also are other design matters like certificates, badges, event tags for particants. And not to mention the entire site with design and maintanence. </p>
